-- Add column visibility management

-- Insert default columns with their standard labels
INSERT INTO public.column_visibility (column_name, column_label, visible, display_order)
VALUES
  ('firstname', 'First Name', true, 1),
  ('surname', 'Surname', true, 2),
  ('email', 'Email', true, 3),
  ('phone', 'Phone', true, 4),
  ('birthdate', 'Birth Date', false, 5),
  ('birthmonth', 'Birth Month', false, 6),
  ('birthyear', 'Birth Year', false, 7),
  ('street_address', 'Street Address', false, 8),
  ('municipality', 'Municipality', false, 9),
  ('division', 'Division', false, 10),
  ('region', 'Region', false, 11),
  ('country', 'Country', false, 12),
  ('postcode', 'Postcode', false, 13),
  ('federal_electoral_district', 'Federal Electoral District', false, 14),
  ('division_electoral_district', 'Division Electoral District', true, 15),
  ('municipal_electoral_district', 'Municipal Electoral District', false, 16),
  ('ballot1', 'Ballot 1', false, 17),
  ('ballot2', 'Ballot 2', false, 18),
  ('ballot3', 'Ballot 3', false, 19),
  ('ballot4', 'Ballot 4', false, 20),
  ('comms_consent', 'Comms Consent', false, 21),
  ('signup_consent', 'Signup Consent', false, 22),
  ('signup_submitted', 'Signup Submitted', false, 23),
  ('member', 'Member', false, 24),
  ('organizer', 'Organizer', true, 25),
  ('language', 'Language', false, 26),
  ('olp23_ballot1', 'OLP23 Ballot 1', false, 27),
  ('olp23_ballot2', 'OLP23 Ballot 2', false, 28),
  ('olp23_ballot3', 'OLP23 Ballot 3', false, 29),
  ('olp23_ballot4', 'OLP23 Ballot 4', false, 30),
  ('olp23_comms_consent', 'OLP23 Comms Consent', false, 31),
  ('olp23_signup_consent', 'OLP23 Signup Consent', false, 32),
  ('olp23_volunteer_status', 'OLP23 Volunteer Status', false, 33),
  ('olp23_donor_status', 'OLP23 Donor Status', false, 34),
  ('olp23_donation_amount', 'OLP23 Donation Amount', false, 35),
  ('olp23_signup_submitted', 'OLP23 Signup Submitted', false, 36),
  ('olp23_organizer', 'OLP23 Organizer', false, 37),
  ('olp23_source', 'OLP23 Source', false, 38),
  ('olp23_member', 'OLP23 Member', false, 39),
  ('olp23_voted', 'OLP23 Voted', false, 40),
  ('olp23_voting_group', 'OLP23 Voting Group', false, 41),
  ('olp23_voting_location', 'OLP23 Voting Location', false, 42),
  ('olp23_voting_period', 'OLP23 Voting Period', false, 43),
  ('olp23_voting_association', 'OLP23 Voting Association', false, 44),
  ('olp23_nate_signup', 'OLP23 Nate Signup', false, 45),
  ('olp23_campus_club', 'OLP23 Campus Club', false, 46),
  ('olp23_callhub_notes', 'OLP23 Callhub Notes', false, 47),
  ('olp23_nes_support_level', 'OLP23 NES Support Level', false, 48),
  ('olp23_gender', 'OLP23 Gender', false, 49),
  ('olp23_riding', 'OLP23 Riding', false, 50),
  ('olp23_organizer_ref_id', 'OLP23 Organizer Ref ID', false, 51),
  ('olp23_membership_status', 'OLP23 Membership Status', false, 52),
  ('olp_van_id', 'OLP VAN ID', false, 53),
  ('lpc_van_id', 'LPC VAN ID', false, 54),
  ('tags', 'Tags', false, 55),
  ('gender', 'Gender', false, 56),
  ('mailerlite_id', 'Mailerlite ID', false, 57),
  ('campus_club', 'Campus Club', true, 58),
  ('ride_request_status', 'Ride Request Status', false, 59),
  ('contact_status', 'Contact Status', false, 60)
ON CONFLICT (column_name) DO NOTHING;
