INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Ajax', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Algoma—Manitoulin', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Aurora—Oak Ridges—Richmond Hill', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Barrie—Innisfil', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Barrie—Springwater—Oro-Medonte', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Bay of Quinte', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Beaches—East York', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Brampton Centre', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Brampton East', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Brampton North', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Brampton South', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Brampton West', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Brantford—Brant', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Bruce—Grey—Owen Sound', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Burlington', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Cambridge', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Carleton', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Chatham-Kent—Leamington', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Davenport', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Don Valley East', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Don Valley North', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Don Valley West', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Dufferin—Caledon', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Durham', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Eglinton—Lawrence', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Elgin—Middlesex—London', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Essex', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Etobicoke Centre', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Etobicoke North', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Etobicoke—Lakeshore', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Flamborough—Glanbrook', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Glengarry—Prescott—Russell', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Guelph', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Haldimand—Norfolk', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Haliburton—Kawartha Lakes—Brock', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Hamilton Centre', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Hamilton East—Stoney Creek', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Hamilton Mountain', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Hamilton West—Ancaster—Dundas', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Hastings—Lennox and Addington', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Humber River—Black Creek', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Huron—Bruce', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Kanata—Carleton', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Kenora—Rainy River', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Kiiwetinoong', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('King—Vaughan', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Kingston and the Islands', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Kitchener Centre', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Kitchener South—Hespeler', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Kitchener—Conestoga', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Lambton—Kent—Middlesex', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Lanark—Frontenac—Kingston', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Leeds—Grenville—Thousand Islands and Rideau Lakes', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('London North Centre', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('London West', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('London—Fanshawe', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Markham—Stouffville', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Markham—Thornhill', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Markham—Unionville', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Milton', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Mississauga Centre', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Mississauga East—Cooksville', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Mississauga—Erin Mills', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Mississauga—Lakeshore', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Mississauga—Malton', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Mississauga—Streetsville', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Mushkegowuk—James Bay', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Nepean', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Newmarket—Aurora', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Niagara Centre', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Niagara Falls', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Niagara West', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Nickel Belt', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Nipissing', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Northumberland—Peterborough South', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Oakville', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Oakville North—Burlington', 'central_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Orléans', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Oshawa', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Ottawa Centre', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Ottawa South', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Ottawa West—Nepean', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Ottawa—Vanier', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Oxford', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Parkdale—High Park', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Parry Sound—Muskoka', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Perth—Wellington', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Peterborough—Kawartha', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Pickering—Uxbridge', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Renfrew—Nipissing—Pembroke', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Richmond Hill', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Sarnia—Lambton', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Sault Ste. Marie', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Scarborough Centre', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Scarborough North', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Scarborough Southwest', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Scarborough—Agincourt', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Scarborough—Guildwood', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Scarborough—Rouge Park', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Simcoe North', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Simcoe—Grey', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Spadina—Fort York', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('St. Catharines', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Stormont—Dundas—South Glengarry', 'east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Sudbury', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Thornhill', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Thunder Bay—Atikokan', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Thunder Bay—Superior North', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Timiskaming—Cochrane', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Timmins', 'north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Toronto Centre', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Toronto—Danforth', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Toronto—St. Paul''s', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('University—Rosedale', 'toronto_ede');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Vaughan—Woodbridge', 'central_north');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Waterloo', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Wellington—Halton Hills', 'south_central');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Whitby', 'central_east');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Willowdale', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Windsor West', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('Windsor—Tecumseh', 'south_west');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('York Centre', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('York South—Weston', 'toronto_yns');
INSERT INTO "division_electoral_district" ("name", "olp_region") VALUES ('York—Simcoe', 'central_north');
