name: Deploy Lambda

on:
  push:
    branches:
      - main
    # Optional: ignore docs or workflow-only changes
    # paths-ignore:
    #  - "*.md"
    #  - ".github/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      S3_BUCKET: nesrm-mailerlite-load
      S3_KEY: src.zip
      LAMBDA_FUNCTION_NAME: nesrm-mailerlite_load

    steps:
      # Checkout repository with submodules
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive # ensures vendor/mailerlite_load is fully fetched

      # Setup AWS CLI
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role
          aws-region: us-east-1

      # Create new package
      - name: Creeate lambda package dir
        run: |
          mkdir lambda_env

      # Download existing Lambda package (if exists)
      # - name: Download existing Lambda package
      #  run: |
      #    if aws s3 ls s3://$S3_BUCKET/$S3_KEY ; then
      #        aws s3 cp s3://$S3_BUCKET/$S3_KEY existing_lambda.zip
      #        unzip -q existing_lambda.zip -d lambda_env
      #    fi
      # Copy entire repo into lambda_env
      - name: Copy repository to lambda_env
        run: |
          rsync -a --exclude='lambda_env' --exclude='.git*' --exclude='.env' --exclude='.github' ./ lambda_env/
        # interesting quirk. rsync allegedly wouldn't exclude .github off of .git* alone. You need .git*/ but I haven't tested this

      # Zip Lambda package
      - name: Zip Lambda package
        run: |
          cd lambda_env
          zip -r ../updated-lambda.zip .
          cd ..

      # Upload to S3 and update Lambda
      - name: Upload to S3 and update Lambda
        run: |
          aws s3 cp updated-lambda.zip s3://$S3_BUCKET/$S3_KEY
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --s3-bucket $S3_BUCKET \
            --s3-key $S3_KEY

      # Cleanup
      - name: Cleanup
        run: |
          rm -rf lambda_env existing_lambda.zip updated-lambda.zip
