-- Add GOTV fields: ride_request_status, contact_status, and voting history table

-- Add status fields to contact table
ALTER TABLE public.contact
  ADD COLUMN IF NOT EXISTS ride_request_status text,
  ADD COLUMN IF NOT EXISTS contact_status text;

-- Create contact_voting_history table to track voting status changes
CREATE TABLE IF NOT EXISTS public.contact_voting_history (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  contact_id bigint NOT NULL,
  voted boolean NOT NULL,
  marked_by uuid,
  marked_at timestamp with time zone DEFAULT now() NOT NULL,
  notes text,
  CONSTRAINT contact_voting_history_pkey PRIMARY KEY (id),
  CONSTRAINT contact_voting_history_contact_id_fkey FOREIGN KEY (contact_id)
    REFERENCES public.contact(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT contact_voting_history_marked_by_fkey FOREIGN KEY (marked_by)
    REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Create index on contact_id for efficient lookups
CREATE INDEX IF NOT EXISTS contact_voting_history_contact_id_idx 
  ON public.contact_voting_history(contact_id);

-- Enable RLS on the new table
ALTER TABLE public.contact_voting_history ENABLE ROW LEVEL SECURITY;

-- Grant permissions (following the pattern from contact table)
GRANT ALL ON TABLE public.contact_voting_history TO anon;
GRANT ALL ON TABLE public.contact_voting_history TO authenticated;
GRANT ALL ON TABLE public.contact_voting_history TO service_role;

GRANT ALL ON SEQUENCE public.contact_voting_history_id_seq TO anon;
GRANT ALL ON SEQUENCE public.contact_voting_history_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.contact_voting_history_id_seq TO service_role;

-- Create policy to allow authenticated users to read voting history for contacts they can access
-- This follows the same pattern as the contact access policy
CREATE POLICY "allow authenticated voting history by contact access"
  ON public.contact_voting_history
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.contact c
      WHERE c.id = contact_voting_history.contact_id
        AND c.organizer is not null
        AND (
          EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.organizer_tag is not null
              AND c.organizer ilike '%' || p.organizer_tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profile_organizer_tags pot
            WHERE pot.profile_id = auth.uid()
              AND pot.tag is not null
              AND c.organizer ilike '%' || pot.tag || '%'
          )
        )
    )
  );

-- Allow authenticated users to insert voting history (when they mark someone as voted)
CREATE POLICY "allow authenticated insert voting history"
  ON public.contact_voting_history
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.contact c
      WHERE c.id = contact_voting_history.contact_id
        AND c.organizer is not null
        AND (
          EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.organizer_tag is not null
              AND c.organizer ilike '%' || p.organizer_tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profile_organizer_tags pot
            WHERE pot.profile_id = auth.uid()
              AND pot.tag is not null
              AND c.organizer ilike '%' || pot.tag || '%'
          )
        )
    )
    AND marked_by = auth.uid()
  );

