SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE TYPE public.role_type AS ENUM ('super_admin', 'admin', 'member');
CREATE TYPE public.filter_visibility AS ENUM ('private', 'team');

CREATE TABLE public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    email text NOT NULL UNIQUE,
    first_name text NOT NULL,
    surname text NOT NULL,
    phone text NOT NULL,
    street_address text NOT NULL,
    postal_code text NOT NULL,
    birth_year smallint NOT NULL,
    birth_month smallint NOT NULL,
    birth_day smallint NOT NULL,
    organizer_tag text NOT NULL UNIQUE,
    role role_type NOT NULL DEFAULT 'member'
);

CREATE TABLE public.organizer_tags (
    tag text PRIMARY KEY,
    display_name text NOT NULL,
    created_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.profile_organizer_tags (
    profile_id uuid REFERENCES public.profiles (id) ON DELETE CASCADE,
    tag text REFERENCES public.organizer_tags (tag) ON DELETE CASCADE,
    PRIMARY KEY (profile_id, tag)
);

CREATE TABLE public.profile_riding_access (
    profile_id uuid REFERENCES public.profiles (id) ON DELETE CASCADE,
    riding text REFERENCES public.division_electoral_district (name) ON DELETE CASCADE,
    can_write boolean NOT NULL DEFAULT false,
    granted_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, riding)
);

CREATE TABLE public.profile_region_access (
    profile_id uuid REFERENCES public.profiles (id) ON DELETE CASCADE,
    region text NOT NULL,
    can_write boolean NOT NULL DEFAULT false,
    granted_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, region)
);

CREATE TABLE public.profile_campus_club_access (
    profile_id uuid REFERENCES public.profiles (id) ON DELETE CASCADE,
    campus_club text NOT NULL,
    can_write boolean NOT NULL DEFAULT false,
    granted_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, campus_club)
);

CREATE TABLE public.signup_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'pending',
    email text NOT NULL,
    password_hash text NOT NULL,
    first_name text NOT NULL,
    surname text NOT NULL,
    phone text NOT NULL,
    street_address text NOT NULL,
    postal_code text NOT NULL,
    birth_year smallint NOT NULL,
    birth_month smallint NOT NULL,
    birth_day smallint NOT NULL,
    comms_consent boolean NOT NULL,
    signup_consent boolean NOT NULL,
    wants_student_club boolean NOT NULL,
    campus_club text,
    associations text[] NOT NULL DEFAULT '{}',
    organizer_tag text NOT NULL,
    reviewer_id uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    reviewer_notes text,
    UNIQUE (email)
);

CREATE TABLE public.saved_filters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    name text NOT NULL,
    owner_id uuid REFERENCES public.profiles (id) ON DELETE CASCADE,
    visibility filter_visibility NOT NULL DEFAULT 'private',
    config jsonb NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizer_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_organizer_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_riding_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_region_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_campus_club_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signup_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_filters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Allow service manage profiles" ON public.profiles
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow service manage signup requests" ON public.signup_requests
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow service manage access tables" ON public.profile_organizer_tags
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow service manage access tables regions" ON public.profile_region_access
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow service manage access tables ridings" ON public.profile_riding_access
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow service manage campus club access" ON public.profile_campus_club_access
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated read organizer tags" ON public.organizer_tags
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated read access scopes" ON public.profile_organizer_tags
    FOR SELECT TO authenticated USING (auth.uid() = profile_id);

CREATE POLICY "Allow authenticated read riding access" ON public.profile_riding_access
    FOR SELECT TO authenticated USING (auth.uid() = profile_id);

CREATE POLICY "Allow authenticated read region access" ON public.profile_region_access
    FOR SELECT TO authenticated USING (auth.uid() = profile_id);

CREATE POLICY "Allow authenticated read campus access" ON public.profile_campus_club_access
    FOR SELECT TO authenticated USING (auth.uid() = profile_id);

CREATE POLICY "Allow authenticated read saved filters" ON public.saved_filters
    FOR SELECT TO authenticated USING (
        owner_id = auth.uid() OR visibility = 'team'
    );

CREATE POLICY "Allow service manage saved filters" ON public.saved_filters
    FOR ALL TO service_role USING (true) WITH CHECK (true);
