-- Add custom columns feature: custom_columns and contact_custom_fields tables

-- Create custom_columns table to store column definitions
CREATE TABLE IF NOT EXISTS public.custom_columns (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  label text NOT NULL,
  data_type text NOT NULL CHECK (data_type IN ('text', 'number', 'date', 'boolean', 'select')),
  options jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  created_by uuid,
  CONSTRAINT custom_columns_pkey PRIMARY KEY (id),
  CONSTRAINT custom_columns_name_key UNIQUE (name),
  CONSTRAINT custom_columns_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Create contact_custom_fields table to store actual field values
CREATE TABLE IF NOT EXISTS public.contact_custom_fields (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  contact_id bigint NOT NULL,
  column_id bigint NOT NULL,
  value_text text,
  value_number numeric,
  value_date date,
  value_boolean boolean,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT contact_custom_fields_pkey PRIMARY KEY (id),
  CONSTRAINT contact_custom_fields_contact_id_fkey FOREIGN KEY (contact_id)
    REFERENCES public.contact(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT contact_custom_fields_column_id_fkey FOREIGN KEY (column_id)
    REFERENCES public.custom_columns(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT contact_custom_fields_contact_column_unique UNIQUE (contact_id, column_id)
);

-- Create indexes for efficient lookups
CREATE INDEX IF NOT EXISTS custom_columns_name_idx ON public.custom_columns(name);
CREATE INDEX IF NOT EXISTS contact_custom_fields_contact_id_idx ON public.contact_custom_fields(contact_id);
CREATE INDEX IF NOT EXISTS contact_custom_fields_column_id_idx ON public.contact_custom_fields(column_id);

-- Create trigger to update updated_at on custom_columns
CREATE OR REPLACE FUNCTION update_custom_columns_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_custom_columns_updated_at
  BEFORE UPDATE ON public.custom_columns
  FOR EACH ROW
  EXECUTE FUNCTION update_custom_columns_updated_at();

-- Create trigger to update updated_at on contact_custom_fields
CREATE OR REPLACE FUNCTION update_contact_custom_fields_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_contact_custom_fields_updated_at
  BEFORE UPDATE ON public.contact_custom_fields
  FOR EACH ROW
  EXECUTE FUNCTION update_contact_custom_fields_updated_at();

-- Enable RLS on both tables
ALTER TABLE public.custom_columns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_custom_fields ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON TABLE public.custom_columns TO anon;
GRANT ALL ON TABLE public.custom_columns TO authenticated;
GRANT ALL ON TABLE public.custom_columns TO service_role;

GRANT ALL ON TABLE public.contact_custom_fields TO anon;
GRANT ALL ON TABLE public.contact_custom_fields TO authenticated;
GRANT ALL ON TABLE public.contact_custom_fields TO service_role;

GRANT ALL ON SEQUENCE public.custom_columns_id_seq TO anon;
GRANT ALL ON SEQUENCE public.custom_columns_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.custom_columns_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.contact_custom_fields_id_seq TO anon;
GRANT ALL ON SEQUENCE public.contact_custom_fields_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.contact_custom_fields_id_seq TO service_role;

-- RLS Policies for custom_columns
-- Allow all authenticated users to read custom columns
CREATE POLICY "allow authenticated read custom_columns"
  ON public.custom_columns
  FOR SELECT
  TO authenticated
  USING (true);

-- Allow admins to insert custom columns
CREATE POLICY "allow admin insert custom_columns"
  ON public.custom_columns
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('super_admin', 'admin')
    )
    AND created_by = auth.uid()
  );

-- Allow admins to update custom columns
CREATE POLICY "allow admin update custom_columns"
  ON public.custom_columns
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('super_admin', 'admin')
    )
  );

-- Allow admins to delete custom columns
CREATE POLICY "allow admin delete custom_columns"
  ON public.custom_columns
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('super_admin', 'admin')
    )
  );

-- RLS Policies for contact_custom_fields
-- Allow authenticated users to read custom fields for contacts they can access
CREATE POLICY "allow authenticated read contact_custom_fields"
  ON public.contact_custom_fields
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.contact c
      WHERE c.id = contact_custom_fields.contact_id
        AND (
          -- Allow if contact has no organizer restriction
          c.organizer IS NULL
          -- Or if user has access via organizer tag
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.organizer_tag IS NOT NULL
              AND c.organizer ILIKE '%' || p.organizer_tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profile_organizer_tags pot
            WHERE pot.profile_id = auth.uid()
              AND pot.tag IS NOT NULL
              AND c.organizer ILIKE '%' || pot.tag || '%'
          )
          -- Or if user is admin
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('super_admin', 'admin')
          )
        )
    )
  );

-- Allow authenticated users to insert/update custom fields for contacts they can access
CREATE POLICY "allow authenticated modify contact_custom_fields"
  ON public.contact_custom_fields
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.contact c
      WHERE c.id = contact_custom_fields.contact_id
        AND (
          -- Allow if contact has no organizer restriction
          c.organizer IS NULL
          -- Or if user has access via organizer tag
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.organizer_tag IS NOT NULL
              AND c.organizer ILIKE '%' || p.organizer_tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profile_organizer_tags pot
            WHERE pot.profile_id = auth.uid()
              AND pot.tag IS NOT NULL
              AND c.organizer ILIKE '%' || pot.tag || '%'
          )
          -- Or if user is admin
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('super_admin', 'admin')
          )
        )
    )
  );