-- Create table for survey column update rules
-- Allows multiple rules per question and supports both question-level and survey-level rules

CREATE TABLE IF NOT EXISTS "public"."survey_column_update_rules" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_by" uuid REFERENCES "public"."profiles"("id") ON DELETE SET NULL,
  "updated_by" uuid REFERENCES "public"."profiles"("id") ON DELETE SET NULL,
  
  -- Rule scope: either question_id OR survey_id must be set (not both)
  "question_id" bigint REFERENCES "public"."survey_questions"("id") ON DELETE CASCADE,
  "survey_id" bigint REFERENCES "public"."surveys"("id") ON DELETE CASCADE,
  
  -- Rule configuration (stored as JSONB for flexibility)
  "rule_config" jsonb NOT NULL,
  
  -- Rule metadata
  "enabled" boolean DEFAULT true NOT NULL,
  "priority" integer DEFAULT 0 NOT NULL,
  "description" text,
  "tags" text[],
  
  -- Audit fields
  "last_applied_at" timestamp with time zone,
  "application_count" bigint DEFAULT 0,
  
  CONSTRAINT "survey_column_update_rules_scope_check" 
    CHECK (
      (question_id IS NOT NULL AND survey_id IS NULL) OR 
      (question_id IS NULL AND survey_id IS NOT NULL)
    )
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS "survey_column_update_rules_question_id_idx" 
  ON "public"."survey_column_update_rules"("question_id");
  
CREATE INDEX IF NOT EXISTS "survey_column_update_rules_survey_id_idx" 
  ON "public"."survey_column_update_rules"("survey_id");
  
CREATE INDEX IF NOT EXISTS "survey_column_update_rules_enabled_priority_idx" 
  ON "public"."survey_column_update_rules"("enabled", "priority");

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_survey_column_update_rules_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_survey_column_update_rules_updated_at
  BEFORE UPDATE ON "public"."survey_column_update_rules"
  FOR EACH ROW
  EXECUTE FUNCTION update_survey_column_update_rules_updated_at();

COMMENT ON TABLE "public"."survey_column_update_rules" IS 'Stores column update rules for survey responses. Rules can be scoped to a specific question or to the entire survey.';
COMMENT ON COLUMN "public"."survey_column_update_rules"."rule_config" IS 'JSONB field storing the comprehensive ColumnUpdateRule configuration';
COMMENT ON COLUMN "public"."survey_column_update_rules"."question_id" IS 'If set, this rule applies only to answers for this specific question';
COMMENT ON COLUMN "public"."survey_column_update_rules"."survey_id" IS 'If set, this rule applies to all answers in the survey (survey-level rule)';
COMMENT ON COLUMN "public"."survey_column_update_rules"."priority" IS 'Lower numbers execute first. Default is 0.';
COMMENT ON COLUMN "public"."survey_column_update_rules"."application_count" IS 'Number of times this rule has been successfully applied';
