-- Create page_questions junction table to link questions to reusable pages
CREATE TABLE IF NOT EXISTS "public"."page_questions" (
    "id" bigint NOT NULL,
    "page_id" bigint NOT NULL,
    "question_id" bigint NOT NULL,
    "question_order" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "page_questions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "page_questions_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."survey_pages"("id") ON DELETE CASCADE,
    CONSTRAINT "page_questions_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."survey_questions"("id") ON DELETE CASCADE,
    CONSTRAINT "page_questions_page_question_unique" UNIQUE ("page_id", "question_id")
);

ALTER TABLE "public"."page_questions" OWNER TO "postgres";

COMMENT ON TABLE "public"."page_questions" IS 'Junction table linking reusable pages to questions. Questions can be shared across multiple pages.';

COMMENT ON COLUMN "public"."page_questions"."question_order" IS '1-indexed order of the question within the page';

ALTER TABLE "public"."page_questions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."page_questions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Create indexes for efficient lookups
CREATE INDEX "page_questions_page_id_idx" ON "public"."page_questions" USING "btree" ("page_id");
CREATE INDEX "page_questions_question_id_idx" ON "public"."page_questions" USING "btree" ("question_id");
CREATE INDEX "page_questions_page_order_idx" ON "public"."page_questions" USING "btree" ("page_id", "question_order");

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE TRIGGER "update_page_questions_updated_at" 
BEFORE UPDATE ON "public"."page_questions" 
FOR EACH ROW 
EXECUTE FUNCTION "public"."update_updated_at_column"();

-- Enable RLS
ALTER TABLE "public"."page_questions" ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Allow admins to manage page_questions
CREATE POLICY "allow admin manage page_questions" ON "public"."page_questions"
TO "authenticated"
USING (
    EXISTS (
        SELECT 1
        FROM "public"."profiles"
        WHERE "profiles"."id" = auth.uid()
        AND "profiles"."role" IN ('super_admin', 'admin')
    )
);

-- Grant permissions
GRANT ALL ON TABLE "public"."page_questions" TO "anon";
GRANT ALL ON TABLE "public"."page_questions" TO "authenticated";
GRANT ALL ON TABLE "public"."page_questions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."page_questions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."page_questions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."page_questions_id_seq" TO "service_role";
