-- Create campaign system tables

-- 1. campaigns - Generic campaign table for surveys, emails, SMS
CREATE TABLE IF NOT EXISTS public.campaigns (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  campaign_type text NOT NULL CHECK (campaign_type IN ('survey', 'email', 'sms')),
  content_id bigint NOT NULL,
  name text NOT NULL,
  description text,
  config jsonb NOT NULL,
  status text NOT NULL CHECK (status IN ('draft', 'scheduled', 'sending', 'sent', 'cancelled')) DEFAULT 'draft',
  scheduled_at timestamptz,
  total_recipients integer DEFAULT 0,
  sent_count integer DEFAULT 0,
  archived boolean DEFAULT false,
  failed_contact_ids jsonb,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id)
);

-- 2. audiences - Reusable audience definitions
CREATE TABLE IF NOT EXISTS public.audiences (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  name text NOT NULL,
  description text,
  config jsonb NOT NULL,
  visibility text NOT NULL CHECK (visibility IN ('private', 'team')) DEFAULT 'private',
  last_contact_count integer,
  last_calculated_at timestamptz,
  CONSTRAINT audiences_pkey PRIMARY KEY (id)
);

-- 3. Add foreign key constraint to campaign_id in survey_instances
-- Note: The column was added in the survey system migration, we just need to add the FK constraint
DO $$
BEGIN
  -- Add the column if it doesn't exist (for backward compatibility with older deployments)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'survey_instances' 
    AND column_name = 'campaign_id'
  ) THEN
    ALTER TABLE public.survey_instances 
    ADD COLUMN campaign_id bigint;
  END IF;
  
  -- Add foreign key constraint if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_schema = 'public' 
    AND table_name = 'survey_instances' 
    AND constraint_name = 'survey_instances_campaign_id_fkey'
  ) THEN
    ALTER TABLE public.survey_instances 
    ADD CONSTRAINT survey_instances_campaign_id_fkey 
    FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE SET NULL;
  END IF;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS campaigns_created_by_idx ON public.campaigns(created_by);
CREATE INDEX IF NOT EXISTS campaigns_campaign_type_content_id_idx ON public.campaigns(campaign_type, content_id);
CREATE INDEX IF NOT EXISTS campaigns_status_idx ON public.campaigns(status);
CREATE INDEX IF NOT EXISTS campaigns_archived_idx ON public.campaigns(archived);
CREATE INDEX IF NOT EXISTS audiences_created_by_idx ON public.audiences(created_by);
CREATE INDEX IF NOT EXISTS audiences_visibility_idx ON public.audiences(visibility);
CREATE INDEX IF NOT EXISTS survey_instances_campaign_id_idx ON public.survey_instances(campaign_id);

-- Create triggers for updated_at
CREATE TRIGGER update_campaigns_updated_at
  BEFORE UPDATE ON public.campaigns
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_audiences_updated_at
  BEFORE UPDATE ON public.audiences
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audiences ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON TABLE public.campaigns TO anon;
GRANT ALL ON TABLE public.campaigns TO authenticated;
GRANT ALL ON TABLE public.campaigns TO service_role;

GRANT ALL ON TABLE public.audiences TO anon;
GRANT ALL ON TABLE public.audiences TO authenticated;
GRANT ALL ON TABLE public.audiences TO service_role;

-- Grant sequence permissions
GRANT ALL ON SEQUENCE public.campaigns_id_seq TO anon;
GRANT ALL ON SEQUENCE public.campaigns_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.campaigns_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.audiences_id_seq TO anon;
GRANT ALL ON SEQUENCE public.audiences_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.audiences_id_seq TO service_role;

-- RLS Policies for campaigns
-- Admins can manage all campaigns
CREATE POLICY "allow admin manage campaigns"
  ON public.campaigns
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  );

-- RLS Policies for audiences
-- Admins can manage all audiences
CREATE POLICY "allow admin manage audiences"
  ON public.audiences
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  );

-- Setup pgmq queue for survey_send if extension exists
DO $$
BEGIN
  -- Check if pgmq extension exists
  IF EXISTS (
    SELECT 1 FROM pg_extension WHERE extname = 'pgmq'
  ) THEN
    -- Create queue if it doesn't exist
    PERFORM * FROM pgmq.create('survey_send');
  END IF;
END $$;

