-- Create survey system tables

-- 1. survey_questions - Reusable question library
CREATE TABLE IF NOT EXISTS public.survey_questions (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  question_text text NOT NULL,
  question_type text NOT NULL CHECK (question_type IN ('text', 'textarea', 'multiple_choice', 'checkbox', 'number', 'date', 'email')),
  options jsonb,
  required boolean DEFAULT false,
  validation_config jsonb,
  archived boolean DEFAULT false,
  CONSTRAINT survey_questions_pkey PRIMARY KEY (id)
);

-- 2. surveys - Survey definitions
CREATE TABLE IF NOT EXISTS public.surveys (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  status text NOT NULL CHECK (status IN ('draft', 'active', 'closed')),
  structure jsonb NOT NULL,
  settings jsonb,
  archived boolean DEFAULT false,
  CONSTRAINT surveys_pkey PRIMARY KEY (id)
);

-- 3. survey_instances - Tracks survey distribution to contacts
CREATE TABLE IF NOT EXISTS public.survey_instances (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  survey_id bigint NOT NULL REFERENCES public.surveys(id) ON DELETE RESTRICT,
  contact_id bigint NOT NULL REFERENCES public.contact(id) ON DELETE CASCADE,
  campaign_id bigint, -- Foreign key constraint added in campaign system migration
  sent_at timestamptz,
  sent_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  token text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('pending', 'sent', 'started', 'completed', 'expired')),
  completed_at timestamptz,
  expires_at timestamptz,
  CONSTRAINT survey_instances_pkey PRIMARY KEY (id)
);

-- 4. survey_responses - Individual response records
CREATE TABLE IF NOT EXISTS public.survey_responses (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  survey_instance_id bigint NOT NULL REFERENCES public.survey_instances(id) ON DELETE CASCADE,
  survey_id bigint NOT NULL REFERENCES public.surveys(id) ON DELETE RESTRICT,
  contact_id bigint NOT NULL REFERENCES public.contact(id) ON DELETE CASCADE,
  status text NOT NULL CHECK (status IN ('in_progress', 'completed')),
  started_at timestamptz,
  completed_at timestamptz,
  metadata jsonb,
  CONSTRAINT survey_responses_pkey PRIMARY KEY (id)
);

-- 5. survey_response_answers - Answer values for each question
CREATE TABLE IF NOT EXISTS public.survey_response_answers (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  response_id bigint NOT NULL REFERENCES public.survey_responses(id) ON DELETE CASCADE,
  question_id bigint NOT NULL REFERENCES public.survey_questions(id) ON DELETE RESTRICT,
  answer_text text,
  answer_number numeric,
  answer_date date,
  answer_boolean boolean,
  answer_json jsonb,
  CONSTRAINT survey_response_answers_pkey PRIMARY KEY (id),
  CONSTRAINT survey_response_answers_response_question_unique UNIQUE (response_id, question_id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS survey_questions_created_by_idx ON public.survey_questions(created_by);
CREATE INDEX IF NOT EXISTS survey_questions_archived_idx ON public.survey_questions(archived);
CREATE INDEX IF NOT EXISTS surveys_created_by_idx ON public.surveys(created_by);
CREATE INDEX IF NOT EXISTS surveys_status_idx ON public.surveys(status);
CREATE INDEX IF NOT EXISTS surveys_archived_idx ON public.surveys(archived);
CREATE INDEX IF NOT EXISTS survey_instances_survey_id_idx ON public.survey_instances(survey_id);
CREATE INDEX IF NOT EXISTS survey_instances_contact_id_idx ON public.survey_instances(contact_id);
CREATE INDEX IF NOT EXISTS survey_instances_token_idx ON public.survey_instances(token);
CREATE INDEX IF NOT EXISTS survey_instances_contact_survey_idx ON public.survey_instances(contact_id, survey_id);
CREATE INDEX IF NOT EXISTS survey_responses_survey_instance_id_idx ON public.survey_responses(survey_instance_id);
CREATE INDEX IF NOT EXISTS survey_responses_survey_id_idx ON public.survey_responses(survey_id);
CREATE INDEX IF NOT EXISTS survey_responses_contact_id_idx ON public.survey_responses(contact_id);
CREATE INDEX IF NOT EXISTS survey_response_answers_response_id_idx ON public.survey_response_answers(response_id);
CREATE INDEX IF NOT EXISTS survey_response_answers_question_id_idx ON public.survey_response_answers(question_id);

-- Create triggers for updated_at
CREATE TRIGGER update_survey_questions_updated_at
  BEFORE UPDATE ON public.survey_questions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_surveys_updated_at
  BEFORE UPDATE ON public.surveys
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_survey_instances_updated_at
  BEFORE UPDATE ON public.survey_instances
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_survey_responses_updated_at
  BEFORE UPDATE ON public.survey_responses
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_survey_response_answers_updated_at
  BEFORE UPDATE ON public.survey_response_answers
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE public.survey_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_response_answers ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON TABLE public.survey_questions TO anon;
GRANT ALL ON TABLE public.survey_questions TO authenticated;
GRANT ALL ON TABLE public.survey_questions TO service_role;

GRANT ALL ON TABLE public.surveys TO anon;
GRANT ALL ON TABLE public.surveys TO authenticated;
GRANT ALL ON TABLE public.surveys TO service_role;

GRANT ALL ON TABLE public.survey_instances TO anon;
GRANT ALL ON TABLE public.survey_instances TO authenticated;
GRANT ALL ON TABLE public.survey_instances TO service_role;

GRANT ALL ON TABLE public.survey_responses TO anon;
GRANT ALL ON TABLE public.survey_responses TO authenticated;
GRANT ALL ON TABLE public.survey_responses TO service_role;

GRANT ALL ON TABLE public.survey_response_answers TO anon;
GRANT ALL ON TABLE public.survey_response_answers TO authenticated;
GRANT ALL ON TABLE public.survey_response_answers TO service_role;

-- Grant sequence permissions
GRANT ALL ON SEQUENCE public.survey_questions_id_seq TO anon;
GRANT ALL ON SEQUENCE public.survey_questions_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.survey_questions_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.surveys_id_seq TO anon;
GRANT ALL ON SEQUENCE public.surveys_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.surveys_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.survey_instances_id_seq TO anon;
GRANT ALL ON SEQUENCE public.survey_instances_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.survey_instances_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.survey_responses_id_seq TO anon;
GRANT ALL ON SEQUENCE public.survey_responses_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.survey_responses_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.survey_response_answers_id_seq TO anon;
GRANT ALL ON SEQUENCE public.survey_response_answers_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.survey_response_answers_id_seq TO service_role;

-- RLS Policies for survey_questions
-- Admins can manage all questions
CREATE POLICY "allow admin manage survey_questions"
  ON public.survey_questions
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  );

-- RLS Policies for surveys
-- Admins can manage all surveys
CREATE POLICY "allow admin manage surveys"
  ON public.surveys
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  );

-- Public can read surveys for completion (via service role)
-- Service role handles public access through application logic

-- RLS Policies for survey_instances
-- Admins can manage all instances
CREATE POLICY "allow admin manage survey_instances"
  ON public.survey_instances
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  );

-- Public can read instances by token (handled via service role in application)

-- RLS Policies for survey_responses
-- Admins can manage all responses
CREATE POLICY "allow admin manage survey_responses"
  ON public.survey_responses
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  );

-- Public can insert/update responses (handled via service role in application)

-- RLS Policies for survey_response_answers
-- Admins can manage all answers
CREATE POLICY "allow admin manage survey_response_answers"
  ON public.survey_response_answers
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('super_admin', 'admin')
    )
  );

-- Public can insert/update answers (handled via service role in application)



