

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
   NEW.updated_at = now(); 
   RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."contact" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "firstname" "text",
    "surname" "text",
    "email" "text",
    "phone" "text",
    "birthdate" smallint,
    "birthmonth" smallint,
    "birthyear" smallint,
    "street_address" "text",
    "municipality" "text",
    "division" "text",
    "region" "text",
    "country" "text",
    "postcode" "text",
    "federal_electoral_district" "text",
    "division_electoral_district" "text",
    "municipal_electoral_district" "text",
    "ballot1" "text",
    "ballot2" "text",
    "ballot3" "text",
    "ballot4" "text",
    "comms_consent" boolean,
    "signup_consent" boolean,
    "signup_submitted" boolean,
    "member" boolean,
    "organizer" "text",
    "language" "text",
    "olp23_ballot1" "text",
    "olp23_ballot2" "text",
    "olp23_ballot3" "text",
    "olp23_ballot4" "text",
    "olp23_comms_consent" "text",
    "olp23_signup_consent" "text",
    "olp23_volunteer_status" "text",
    "olp23_donor_status" "text",
    "olp23_donation_amount" "text",
    "olp23_signup_submitted" "text",
    "olp23_organizer" "text",
    "olp23_source" "text",
    "olp23_member" "text",
    "olp23_voted" "text",
    "olp23_voting_group" "text",
    "olp23_voting_location" "text",
    "olp23_voting_period" "text",
    "olp23_voting_association" "text",
    "olp23_nate_signup" "text",
    "olp23_campus_club" "text",
    "olp23_callhub_notes" "text",
    "olp23_nes_support_level" "text",
    "olp23_gender" "text",
    "olp23_riding" "text",
    "olp23_organizer_ref_id" "text",
    "olp23_membership_status" "text",
    "olp_van_id" "text",
    "lpc_van_id" "text",
    "last_request" bigint,
    "tags" "text",
    "gender" "text",
    "mailerlite_id" "text"
);


ALTER TABLE "public"."contact" OWNER TO "postgres";


ALTER TABLE "public"."contact" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contact_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."division_electoral_district" (
    "name" "text" NOT NULL,
    "olp_region" "text" NOT NULL
);


ALTER TABLE "public"."division_electoral_district" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."request" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "origin" "text",
    "payload" "jsonb",
    "ip" "text",
    "email" "text",
    "success" boolean,
    "logs" "jsonb"
);


ALTER TABLE "public"."request" OWNER TO "postgres";


ALTER TABLE "public"."request" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."contact"
    ADD CONSTRAINT "contact_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."division_electoral_district"
    ADD CONSTRAINT "division_electoral_district_division_electoral_district_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."division_electoral_district"
    ADD CONSTRAINT "division_electoral_district_pkey" PRIMARY KEY ("name");



ALTER TABLE ONLY "public"."request"
    ADD CONSTRAINT "requests_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "update_contact_updated_at" BEFORE INSERT OR UPDATE ON "public"."contact" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."contact"
    ADD CONSTRAINT "contact_last_request_fkey" FOREIGN KEY ("last_request") REFERENCES "public"."request"("id") ON UPDATE CASCADE;



CREATE POLICY "allow all actions for anon" ON "public"."contact" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow all actions for anon" ON "public"."request" TO "anon" USING (true) WITH CHECK (true);



ALTER TABLE "public"."contact" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."division_electoral_district" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."request" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";



GRANT ALL ON TABLE "public"."contact" TO "anon";
GRANT ALL ON TABLE "public"."contact" TO "authenticated";
GRANT ALL ON TABLE "public"."contact" TO "service_role";


GRANT ALL ON SEQUENCE "public"."contact_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contact_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contact_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."division_electoral_district" TO "anon";
GRANT ALL ON TABLE "public"."division_electoral_district" TO "authenticated";
GRANT ALL ON TABLE "public"."division_electoral_district" TO "service_role";


GRANT ALL ON TABLE "public"."request" TO "anon";
GRANT ALL ON TABLE "public"."request" TO "authenticated";
GRANT ALL ON TABLE "public"."request" TO "service_role";



GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."requests_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






