-- Add queryable storage for computed custom column values.
-- Used by formula, answer, and submission columns for filter/sort parity.

CREATE TABLE IF NOT EXISTS public.contact_computed_fields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id bigint NOT NULL REFERENCES public.contact(id) ON UPDATE CASCADE ON DELETE CASCADE,
  column_id bigint NOT NULL REFERENCES public.custom_columns(id) ON UPDATE CASCADE ON DELETE CASCADE,
  value_text text NULL,
  value_number numeric NULL,
  value_date date NULL,
  value_boolean boolean NULL,
  computed_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contact_computed_fields_contact_column_unique UNIQUE (contact_id, column_id)
);

CREATE INDEX IF NOT EXISTS contact_computed_fields_contact_id_idx
  ON public.contact_computed_fields (contact_id);

CREATE INDEX IF NOT EXISTS contact_computed_fields_column_id_idx
  ON public.contact_computed_fields (column_id);

CREATE INDEX IF NOT EXISTS contact_computed_fields_column_contact_idx
  ON public.contact_computed_fields (column_id, contact_id);

CREATE INDEX IF NOT EXISTS contact_computed_fields_text_lookup_idx
  ON public.contact_computed_fields (column_id, value_text)
  WHERE value_text IS NOT NULL;

CREATE INDEX IF NOT EXISTS contact_computed_fields_number_lookup_idx
  ON public.contact_computed_fields (column_id, value_number)
  WHERE value_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS contact_computed_fields_date_lookup_idx
  ON public.contact_computed_fields (column_id, value_date)
  WHERE value_date IS NOT NULL;

CREATE INDEX IF NOT EXISTS contact_computed_fields_boolean_lookup_idx
  ON public.contact_computed_fields (column_id, value_boolean)
  WHERE value_boolean IS NOT NULL;

DROP TRIGGER IF EXISTS update_contact_computed_fields_updated_at ON public.contact_computed_fields;
CREATE TRIGGER update_contact_computed_fields_updated_at
  BEFORE UPDATE ON public.contact_computed_fields
  FOR EACH ROW
  EXECUTE FUNCTION public.update_contact_custom_fields_updated_at();

ALTER TABLE public.contact_computed_fields ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow authenticated read contact_computed_fields" ON public.contact_computed_fields;
CREATE POLICY "allow authenticated read contact_computed_fields"
  ON public.contact_computed_fields
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.contact c
      WHERE c.id = contact_computed_fields.contact_id
        AND (
          c.organizer IS NULL
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.organizer_tag IS NOT NULL
              AND c.organizer ILIKE '%' || p.organizer_tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profile_organizer_tags pot
            WHERE pot.profile_id = auth.uid()
              AND pot.tag IS NOT NULL
              AND c.organizer ILIKE '%' || pot.tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('super_admin', 'admin')
          )
        )
    )
  );

DROP POLICY IF EXISTS "allow authenticated modify contact_computed_fields" ON public.contact_computed_fields;
CREATE POLICY "allow authenticated modify contact_computed_fields"
  ON public.contact_computed_fields
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.contact c
      WHERE c.id = contact_computed_fields.contact_id
        AND (
          c.organizer IS NULL
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.organizer_tag IS NOT NULL
              AND c.organizer ILIKE '%' || p.organizer_tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profile_organizer_tags pot
            WHERE pot.profile_id = auth.uid()
              AND pot.tag IS NOT NULL
              AND c.organizer ILIKE '%' || pot.tag || '%'
          )
          OR EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND p.role IN ('super_admin', 'admin')
          )
        )
    )
  );

GRANT ALL ON TABLE public.contact_computed_fields TO anon;
GRANT ALL ON TABLE public.contact_computed_fields TO authenticated;
GRANT ALL ON TABLE public.contact_computed_fields TO service_role;

GRANT ALL ON SEQUENCE public.contact_computed_fields_id_seq TO anon;
GRANT ALL ON SEQUENCE public.contact_computed_fields_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.contact_computed_fields_id_seq TO service_role;
